services:
  _defaults:
      autowire: true
      autoconfigure: true
      public: false

  Plenta\ContaoJobsBasic\EventListener\Contao\GetSearchablePagesListener:
    class: DVC\AdjustPlentaJobsSitemapByEmploymentType\EventListener\Contao\GetSearchablePagesListener
